// <auto-generated />
using System;
using HousingEstateManagement.Domain.Entities;
using HousingEstateManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HousingEstateManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308220648_AddElectionTypeAndOptions")]
    partial class AddElectionTypeAndOptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TargetBlockId")
                        .HasColumnType("int");

                    b.Property<byte>("TargetScope")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TargetBlockId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalApartments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.Dues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MonthYear")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("UserId");

                    b.ToTable("DuesList");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlockId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<byte>("Scope")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<byte>("VoterEligibility")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.ElectionCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VoteCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId");

                    b.ToTable("ElectionCandidates");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BlockId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PerformedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("TargetPool")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("PerformedById");

                    b.ToTable("FinancialTransactions");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.RecurringTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NextExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("TargetPool")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TransactionType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("RecurringTransactions");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("BlockId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.VoterLog", b =>
                {
                    b.Property<int>("ElectionId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ElectionId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("VoterLogs");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("HousingEstateManagement.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedAnnouncements")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HousingEstateManagement.Domain.Entities.Block", "TargetBlock")
                        .WithMany("Announcements")
                        .HasForeignKey("TargetBlockId");

                    b.Navigation("CreatedBy");

                    b.Navigation("TargetBlock");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.Dues", b =>
                {
                    b.HasOne("HousingEstateManagement.Domain.Entities.Block", "Block")
                        .WithMany("DuesList")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingEstateManagement.Domain.Entities.User", "User")
                        .WithMany("DuesList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.Election", b =>
                {
                    b.HasOne("HousingEstateManagement.Domain.Entities.Block", "Block")
                        .WithMany("Elections")
                        .HasForeignKey("BlockId");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.ElectionCandidate", b =>
                {
                    b.HasOne("HousingEstateManagement.Domain.Entities.Election", "Election")
                        .WithMany("Candidates")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HousingEstateManagement.Domain.Entities.User", "User")
                        .WithMany("CandidatesInfo")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("HousingEstateManagement.Domain.Entities.Block", "Block")
                        .WithMany("FinancialTransactions")
                        .HasForeignKey("BlockId");

                    b.HasOne("HousingEstateManagement.Domain.Entities.User", "PerformedBy")
                        .WithMany("PerformedTransactions")
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Block");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.RecurringTransaction", b =>
                {
                    b.HasOne("HousingEstateManagement.Domain.Entities.Block", "Block")
                        .WithMany("RecurringTransactions")
                        .HasForeignKey("BlockId");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.User", b =>
                {
                    b.HasOne("HousingEstateManagement.Domain.Entities.Block", "Block")
                        .WithMany("Users")
                        .HasForeignKey("BlockId");

                    b.Navigation("Block");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.VoterLog", b =>
                {
                    b.HasOne("HousingEstateManagement.Domain.Entities.Election", "Election")
                        .WithMany("VoterLogs")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HousingEstateManagement.Domain.Entities.User", "User")
                        .WithMany("VoterLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.Block", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("DuesList");

                    b.Navigation("Elections");

                    b.Navigation("FinancialTransactions");

                    b.Navigation("RecurringTransactions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.Election", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("VoterLogs");
                });

            modelBuilder.Entity("HousingEstateManagement.Domain.Entities.User", b =>
                {
                    b.Navigation("CandidatesInfo");

                    b.Navigation("CreatedAnnouncements");

                    b.Navigation("DuesList");

                    b.Navigation("PerformedTransactions");

                    b.Navigation("VoterLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
